name: C++ Build

on: [push]

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          [g++-9, g++-10, g++-11, g++-12, clang++-12, clang++-13, clang++-14]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Protobuf
        run: |
          sudo apt update
          sudo apt install libprotoc-dev protobuf-compiler
      - name: Run CMake configure
        env:
          CXX: ${{ matrix.compiler }}
        run: cmake .
      - uses: ammaraskar/gcc-problem-matcher@master
        if: ${{ startsWith( matrix.compiler, 'g++') }}
      - name: Build
        run: make
      - name: Run CTest
        run: ctest .

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode: [default, "13.4.1"]

    steps:
      - uses: actions/checkout@v4
      - name: Install Protobuf
        run: |
          brew install protobuf openssl@1.1
      - name: Select XCode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        if: matrix.xcode != 'default'
      - name: Run CMake configure
        run: cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/
      - name: Build
        run: make
      - name: Run CTest
        run: ctest .
