name: C++ Build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:


jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          [g++-12, g++-13, g++-14, clang++-16, clang++-17, clang++-18]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Protobuf
        run: |
          sudo apt update
          sudo apt install libprotoc-dev protobuf-compiler
      - name: Run CMake configure
        env:
          CXX: ${{ matrix.compiler }}
        run: cmake .
      - uses: ammaraskar/gcc-problem-matcher@master
        if: ${{ startsWith( matrix.compiler, 'g++') }}
      - name: Build
        run: make
      - name: Run CTest
        run: ctest .

  build-macos:
    strategy:
      matrix:
        os: [macos-latest, macos-13]
        xcode: [default]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Protobuf
        run: |
          brew install protobuf openssl@1.1
      - name: Select XCode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        if: matrix.xcode != 'default'
      - name: Run CMake configure
        run: cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/
      - name: Build
        run: make
      - name: Run CTest
        run: ctest .
